server:
  port: 8123
  contextPath: /api/library/versions/1
  baseUrl: http://localhost:${server.port}${server.contextPath}

cors:
  allowedOrigins:
    - 'http://localhost:4200'

management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - prometheus
          - health
  metrics:
    enable[http]: false
    enable[logback]: false
    enable[tomcat]: false
    enable[jvm.classes]: false
